export interface InsightRow {
  id: string;
  callId: string;
  searchScore: number;
  speaker: string;
  productUser: string;
  estimatedAge: string;
  careLevel: number;
  purchasedProduct: string;
  inquirySummary: string;
  satisfactionScore: number;
  categoryLarge: string;
  categorySmall: string;
  triggerDetail: string;
  triggerSummary: string;
  triggerTags: string;
  triggerHearingLevel: number;
  backgroundDetail: string;
  backgroundSummary: string;
  backgroundTags: string;
  backgroundHearingLevel: number;
  currentStateDetail: string;
  currentStateSummary: string;
  currentStateTags: string;
  currentHearingLevel: number;
  emotion: string;
  emotionLevel: number;
  manifestNeeds: string;
  insight: string;
  personalizeScore: number;
  improvementMaterial: string;
  improvementProduct: string;
  improvementService: string;
  needsNovelty: number;
  chatLog: { role: "agent" | "customer"; text: string }[];
}

export const INSIGHT_ROWS: InsightRow[] = [
  {
    id: "1",
    callId: "C10482F15AD43G3928B51B-F6F9C9C6GHB94883-51D3288E8E2",
    searchScore: 0.5,
    speaker: "本人",
    productUser: "本人",
    estimatedAge: "推定困難",
    careLevel: 5,
    purchasedProduct: "商品特定困難",
    inquirySummary: "注文した商品が本来の配達予定日に届かないことについて問い合わせたが、担当窓口ではないため対応できない旨を伝えた。",
    satisfactionScore: 50,
    categoryLarge: "サービス",
    categorySmall: "購入・配送",
    triggerDetail: "注文した商品が本日届くはずだったが、未着で配送状況が不明のため、電話で確認した。",
    triggerSummary: "注文未着で確認したい",
    triggerTags: "配送遅延, 商品未着, 電話確認, 本日配達予定, 配送状況不明",
    triggerHearingLevel: 9,
    backgroundDetail: "60代の夫婦で、入院中の配偶者の生活必需品をオンラインで注文。自宅は地方都市で、日常的に配達に依存。",
    backgroundSummary: "高齢夫婦・入院配偶者の生活必需品購入",
    backgroundTags: "高齢夫婦, 入院配偶者, 生活必需品, オンライン注文, 地方在住",
    backgroundHearingLevel: 5,
    currentStateDetail: "配送遅延で必要な商品が手元に届かず、不安と生活の不便が続く。",
    currentStateSummary: "配送遅延で不安",
    currentStateTags: "配送遅延, 必要商品未着, 不安, 生活不便, 配送依存",
    currentHearingLevel: 5,
    emotion: "不安と焦り",
    emotionLevel: 58,
    manifestNeeds: "未着の注文の配送状況をすぐに確認したい。",
    insight: "配送情報のリアルタイム可視化と遅延時の自動通知が無いと、特に入院中の家族は生活必需品の確保に不安を抱える。",
    personalizeScore: 70,
    improvementMaterial: "追跡可能な環境配慮型包装素材を採用し、包装にQRコードで配送ステータスを表示。",
    improvementProduct: "ウェブとアプリでリアルタイム配送追跡を提供し、遅延予測で自動リマインド通知を実装する。",
    improvementService: "注文問い合わせ専用のチャットボットと電話窓口を統合し、24時間対応で配送ステータスを即時提示。",
    needsNovelty: 30,
    chatLog: [
      { role: "agent", text: "大変お待たせいたしました。カスタマーサービスセンターでございます。" },
      { role: "customer", text: "すみません。" },
      { role: "agent", text: "はい。" },
      { role: "customer", text: "ちょっと問い合わせなんですけれども。" },
      { role: "agent", text: "あはい。" },
      { role: "customer", text: "うーん地方に住んでおりまして。入院のタナカコープっていいますけれども。" },
      { role: "agent", text: "はい。" },
      { role: "customer", text: "んーとお宅に。" },
      { role: "agent", text: "ええ。" },
      { role: "customer", text: "うーん。電話したんですけれども。" },
      { role: "agent", text: "ええ。" },
      { role: "customer", text: "今日届くはずだった問い合わせの電話なんですけどね。" },
      { role: "agent", text: "えっとご注文されてそれが届くはずだったということでございますか。あの一私どものオンラインショップでお買い物をされたということですか。" },
    ],
  },
  {
    id: "2",
    callId: "C10482F15AD23F3928B51B-2C29149G69C858B9-98593432E92",
    searchScore: 0.5,
    speaker: "不明",
    productUser: "その他",
    estimatedAge: "推定困難",
    careLevel: 5,
    purchasedProduct: "複数商品",
    inquirySummary: "ライフサポートヘルスケア様からやわらかケアパッドとフレッシュナップのサンプル提供依頼、カタログ送付方法の確認を行った。",
    satisfactionScore: 80,
    categoryLarge: "商品",
    categorySmall: "商品選択",
    triggerDetail: "ヘルスストア様は薬局チェーンで、店頭に新商品を展示するためサンプルと製品カタログが必要。日常的に医療・介護用品を仕入れ、顧客への提案資料を準備している。",
    triggerSummary: "カタログ取得方法が不明",
    triggerTags: "サンプル提供依頼, 紙カタログ未保有, デジタル版取得不明, 情報取得遅延",
    triggerHearingLevel: 5,
    backgroundDetail: "ヘルスストア様は薬局チェーン、店頭に新商品を展示するためサンプルと製品カタログが必要。日常的に医療・介護用品を仕入れ、顧客への提案資料を準備している。",
    backgroundSummary: "薬局チェーン、新商品展示、医療介護用品仕入れ、顧客提案資料作成、日常業務",
    backgroundTags: "薬局チェーン, 新商品展示, 医療介護用品仕入れ, 顧客提案資料, 日常業務",
    backgroundHearingLevel: 4,
    currentStateDetail: "紙カタログが廃止され、デジタル版の提供手順が整備されていないため、サンプルとカタログの同時送付が遅延し、業務効率が低下している。",
    currentStateSummary: "カタログ不足で業務遅延",
    currentStateTags: "紙カタログ廃止, デジタル提供手順未整備, 同時送付遅延, 業務効率低下, プロセス非標準化",
    currentHearingLevel: 4,
    emotion: "フラストレーションと焦り",
    emotionLevel: 55,
    manifestNeeds: "やわらかケアパッド80cc、フレッシュナップ各種（15cc香り付き、10cc無香料、5cc無香料）を2枚ずつのサンプルと、製品詳細が分かるカタログを提供してください。",
    insight: "B2Bパートナーはオンラインで即時に閲覧できる製品情報と、簡易サンプル提供が受け取れる仕組みを求めており、情報取得のハードルを下げることで販売促進と業務効率化を実現できる。",
    personalizeScore: 78,
    improvementMaterial: "既存のサンプル包装に再生可能な薄型プラスチックを採用し、環境負荷を低減しつつ軽量化で配送コスト削減。",
    improvementProduct: "サンプルパックを統一サイズのミニセット化し、1箱に複数製品を比較できるようにし、顧客が簡単に試せる構成に変更。",
    improvementService: "専用オンラインポータルを設置、QRコードでデジタルカタログ閲覧・サンプル注文を即時に行えるセルフサービスを提供。",
    needsNovelty: 35,
    chatLog: [
      { role: "agent", text: "お電話ありがとうございます。カスタマーセンターでございます。" },
      { role: "customer", text: "あの、ライフサポートヘルスケアと申しますが。" },
      { role: "agent", text: "はい、いつもお世話になっております。" },
      { role: "customer", text: "やわらかケアパッドのサンプルをいただきたいんですけど。" },
      { role: "agent", text: "かしこまりました。何種類ご入用でしょうか。" },
      { role: "customer", text: "80ccと、フレッシュナップも何種類かお願いしたいんですが。" },
      { role: "agent", text: "フレッシュナップですと、15cc香り付き、10cc無香料、5cc無香料がございます。" },
      { role: "customer", text: "それ全部2枚ずつもらえますか。カタログも一緒に送っていただけると助かります。" },
    ],
  },
  {
    id: "3",
    callId: "C10482F15AD23G3928B51B-2E5C4B4194GCB47B-0129G7758C2",
    searchScore: 0.5,
    speaker: "本人",
    productUser: "本人",
    estimatedAge: "推定困難",
    careLevel: 5,
    purchasedProduct: "商品特定困難",
    inquirySummary: "注文の電話をかけたが通話が切れ、再度繋ぎ直しを依頼した。",
    satisfactionScore: 50,
    categoryLarge: "サービス",
    categorySmall: "購入・配送",
    triggerDetail: "通話が途中で切断され、注文手続きが完了できずに苛立ちと不安を感じた。",
    triggerSummary: "通話切断で注文不能",
    triggerTags: "電話切断, 注文未完了, 手続き中断, 苛立ち, 不安",
    triggerHearingLevel: 7,
    backgroundDetail: "40代の主婦で在宅中心、日常的に電話注文を利用し、忙しい生活の中で迅速な購入を求める。",
    backgroundSummary: "在宅主婦、電話注文利用",
    backgroundTags: "40代主婦, 在宅中心, 電話注文利用, 忙しい生活, 迅速な購入志向",
    backgroundHearingLevel: 3,
    currentStateDetail: "通話切断のまま注文が未完了で、再度電話する時間が取れず、商品入手が遅れるリスクがある。",
    currentStateSummary: "注文未完了で遅延リスク",
    currentStateTags: "通話切断継続, 再電話時間不足, 商品入手遅延, リスク認識, 未解決状態",
    currentHearingLevel: 3,
    emotion: "苛立ちと不安",
    emotionLevel: 58,
    manifestNeeds: "電話環境が不安定でも、シームレスに商品を注文できるセルフサービス機能が必要。",
    insight: "電話環境が不安定でも、シームレスに商品を注文できるセルフサービス機能が必要。",
    personalizeScore: 72,
    improvementMaterial: "音声通話品質向上のため、ノイズキャンセリングマイクと高音質コーデックを組み込んだヘッドセット素材を採用。",
    improvementProduct: "注文専用のWeb/アプリ予約システムを導入し、電話不要で商品を即時購入できる機能を追加。",
    improvementService: "通話が切断された際に自動で再接続し、未完了注文を自動で引き継ぐコールバックサービスを提供。",
    needsNovelty: 65,
    chatLog: [
      { role: "agent", text: "お電話ありがとうございます。カスタマーセンターでございます。" },
      { role: "customer", text: "あの、さっき電話が切れてしまいまして。" },
      { role: "agent", text: "大変申し訳ございませんでした。" },
      { role: "customer", text: "注文の途中だったんですけど、また最初からやり直しですか？" },
      { role: "agent", text: "ご注文内容をお伺いできれば、続きから対応させていただきます。" },
      { role: "customer", text: "それは助かります。やわらかケアパッドの120ccを3パックお願いしたいんですが。" },
    ],
  },
  {
    id: "4",
    callId: "C10482F15AD1373928B51B-5A9GF4BCB7FA3AF5-1GAFE9B5112",
    searchScore: 0.5,
    speaker: "本人",
    productUser: "本人",
    estimatedAge: "推定困難",
    careLevel: 5,
    purchasedProduct: "快適フィットマスク",
    inquirySummary: "マスクが箱に直接入っており、個別包装がないことが衛生上懸念という意見。",
    satisfactionScore: 40,
    categoryLarge: "商品",
    categorySmall: "品質・不良",
    triggerDetail: "夜に箱を開けた瞬間、個別包装がなくマスクが直接入っていたことに気付き、埃や微生物が付着しているのでは不安になった。",
    triggerSummary: "個別包装なしでマスクを懸念",
    triggerTags: "衛生リスク, 夜間, 個別包装なし, マスク直接入れ, 汚染不安, 埃・微生物懸念",
    triggerHearingLevel: 7,
    backgroundDetail: "30代の女性、在宅勤務と外出で毎日マスクを使用、衛生意識が高く、家族にも安全な商品を求めている。オンラインで定期購入している。",
    backgroundSummary: "在宅勤務の30代女性、毎日マスク使用で衛生意識高い",
    backgroundTags: "30代女性, 在宅勤務, 毎日マスク使用, 衛生意識高い, オンライン定期購入",
    backgroundHearingLevel: 3,
    currentStateDetail: "個別包装がないことで使用前に汚染を疑い、マスクの使用をためらうことが増え、製品への信頼が低下し、感染不安が日常生活に影響している。",
    currentStateSummary: "衛生不安で使用躊躇、製品信頼低下",
    currentStateTags: "使用前汚染疑念, マスク使用躊躇, 製品信頼低下, 感染不安, 日常生活影響",
    currentHearingLevel: 3,
    emotion: "不安、嫌悪、焦り",
    emotionLevel: 70,
    manifestNeeds: "マスクは個別包装で入れてほしい。",
    insight: "顧客は商品を受け取る時点で完全に清潔であることを求め、包装による二次汚染リスクを排除し、安心して使用できる環境を欲している。",
    personalizeScore: 70,
    improvementMaterial: "既存のプラスチック薄膜を生分解性のPEシートに置き換え、30枚入りでも各マスクを個別密封包装。3層構造で防塵・防菌性能を保持。",
    improvementProduct: "現在の箱包装に個別シール包装を追加。30枚入りでも枚数を真空パウチに入れる、サイズ変更不要で即実装可能。",
    improvementService: "購入ページで「個別包装オプション」を選択できるようにし、専用QRコードで包装衛生説明動画を提供。将来的にAIで包装状態を検査。",
    needsNovelty: 85,
    chatLog: [
      { role: "agent", text: "お電話ありがとうございます。" },
      { role: "customer", text: "あの、快適フィットマスクについてなんですけど。" },
      { role: "agent", text: "はい、どのようなことでしょうか。" },
      { role: "customer", text: "箱を開けたらマスクが直接入ってたんですけど、個別包装とかないんですか？" },
      { role: "agent", text: "ご心配をおかけして申し訳ございません。現在の仕様では個別包装は行っておりません。" },
      { role: "customer", text: "衛生的に大丈夫なんですか？埃とか付いてそうで不安で。" },
      { role: "agent", text: "製造段階でクリーンルームで管理しており、衛生基準は満たしております。ご不安の点はご理解いただけますので、ご意見として承ります。" },
    ],
  },
  {
    id: "5",
    callId: "C10482F15AD0493928B51B-629DE7BA4FE4189 7-A02BE952GA2",
    searchScore: 0.5,
    speaker: "不明",
    productUser: "その他",
    estimatedAge: "推定困難",
    careLevel: 5,
    purchasedProduct: "商品特定困難",
    inquirySummary: "さらさらクールシートに関する問い合わせ。",
    satisfactionScore: 50,
    categoryLarge: "商品",
    categorySmall: "商品選択",
    triggerDetail: "深夜に自宅でさらさらクールシートの効果と使用方法が分からず、購入を躊躇して電話で問い合わせた。",
    triggerSummary: "商品情報が不明で電話問い合わせ",
    triggerTags: "深夜, 自宅, 電話問い合わせ, 確認, 購入躊躇, 製品効果不明",
    triggerHearingLevel: 3,
    backgroundDetail: "40代女性、仕事と育児で忙しく、スキンケアは簡便さを重視。新製品情報を求めている。",
    backgroundSummary: "忙しい40代女性が新製品情報を探す",
    backgroundTags: "40代女性, 仕事と育児の両立, 簡便スキンケア志向, 新製品情報探索, 忙しい生活",
    backgroundHearingLevel: 2,
    currentStateDetail: "製品の具体的な効果や使用手順が分からず、情報不足で購入判断ができない状態。",
    currentStateSummary: "情報不足で購入判断できず",
    currentStateTags: "効果情報不足, 使用手順不明, 購入判断保留, 情報不足, 不安感",
    currentHearingLevel: 2,
    emotion: "不安",
    emotionLevel: 35,
    manifestNeeds: "さらさらクールシートの効果・使用方法と適切な使用頻度を教えてほしい。",
    insight: "信頼できる商品情報が即時に得られないと、自己ケアの効果に不安を抱き、購入をためらう。",
    personalizeScore: 70,
    improvementMaterial: "パッケージにQRコードを付け、動画で使用方法と成分説明を提供し、情報取得を即時化。",
    improvementProduct: "試供品サイズを新設し、実際の使用感を確認できるようにして購入ハードルを下げる。",
    improvementService: "AIチャットボットで24時間商品質問受付、即時に使用方法と効果を提示。オンライン予約でサンプル送付も可能に。",
    needsNovelty: 35,
    chatLog: [
      { role: "agent", text: "お電話ありがとうございます。" },
      { role: "customer", text: "さらさらクールシートっていう商品についてお聞きしたいんですが。" },
      { role: "agent", text: "はい、どのようなことでしょうか。" },
      { role: "customer", text: "どのくらいの頻度で使うものなんですか？毎日使っていいんでしょうか。" },
      { role: "agent", text: "はい、毎日お使いいただける商品です。生理期間外でも日常的にお使いいただけます。" },
      { role: "customer", text: "クール感ってどのくらい続くんですか？" },
      { role: "agent", text: "装着直後から約2〜3時間程度、清涼感が続くように設計されております。" },
    ],
  },
  {
    id: "6",
    callId: "C10482F15AD1413928B51B-29968289736 8C926-C25174145G2",
    searchScore: 0.5,
    speaker: "本人",
    productUser: "本人",
    estimatedAge: "推定困難",
    careLevel: 1,
    purchasedProduct: "商品特定困難",
    inquirySummary: "やわらかケアパッドの吸収別複数商品を電話で注文したい。",
    satisfactionScore: 80,
    categoryLarge: "商品",
    categorySmall: "商品選択",
    triggerDetail: "朝、複数の利用者に適した吸収量のサニタリーパッドを選ぶ際、適切なccが分からず判断に困った。",
    triggerSummary: "吸収量選択で迷い困難",
    triggerTags: "適切な吸収量検索困難, 注文ミスリスク, 在庫切れリスク, 即時検索不可, リスク残存",
    triggerHearingLevel: 2,
    backgroundDetail: "40代の主婦で、家庭内外で軽失禁パッドを複数人分購入し管理している。忙しい生活で迅速な選択が必要。",
    backgroundSummary: "家庭で複数人分のパッドを管理",
    backgroundTags: "40代主婦, 軽失禁パッド, 複数購入管理, 忙しい生活, 迅速な選択",
    backgroundHearingLevel: 3,
    currentStateDetail: "適切な吸収量のパッドがすぐに見つからず、注文ミスや在庫切れのリスクが残っている。",
    currentStateSummary: "選択ミスリスクが残る",
    currentStateTags: "適切吸収量検索困難, 注文ミスリスク, 在庫切れリスク, 即時検索不可, リスク残存",
    currentHearingLevel: 3,
    emotion: "不安と軽い焦り",
    emotionLevel: 30,
    manifestNeeds: "やわらかケアパッドの吸収別（120cc/170cc/220cc/270cc）を複数注文したい。",
    insight: "顧客は利用者ごとの吸収量ニーズに合わせて簡単に適切なパッドを選びたいが、現在のラインナップ表示や選択支援が不十分で、手間と不安が残る。",
    personalizeScore: 70,
    improvementMaterial: "既存の吸収体に可変吸収層を追加、同一素材で複数ccに対応可能な3層構造を導入、製造コストを抑えて3か月で実装。",
    improvementProduct: "パッドパッケージに吸収量コードとQRガイドを付け、オンラインで利用者プロフィールを登録し最適なccを自動提案するサービスを開始。",
    improvementService: "電話注文時にAIチャットが利用者の使用状況を質問し、最適ccを自動選択するサービスを開始、即時確認できるQRコードも配布。",
    needsNovelty: 45,
    chatLog: [
      { role: "agent", text: "お電話ありがとうございます。" },
      { role: "customer", text: "やわらかケアパッドを何種類か注文したいんですけど。" },
      { role: "agent", text: "はい、どの種類をご希望でしょうか。" },
      { role: "customer", text: "120ccと170ccと220ccと270cc、それぞれ何パックか欲しいんですが。" },
      { role: "agent", text: "かしこまりました。それぞれ何パックずつご入用でしょうか。" },
      { role: "customer", text: "120ccを2パック、170ccを3パック、220ccと270ccを1パックずつお願いします。" },
    ],
  },
];
